Nexters/Rollingpaper_client

package-lock.json, package.json, pages/_app.js
- Material UI 설치
- _app.js 파일 추가 
- CssBaseline import하여 css 초기화
=> Material UI 설치 및 _app.js 파일 추가 후 css 초기화

.eslintrc.js, .prettierrc, package-lock.json, package.json, pages/_app.js
#9 
일단 airbnb eslint 는 설치 안하고 기본 eslint, prettier 설정만 했습니다!
=> ESLInt, Prettier 설치 및 기본 설정

components/Layouts.js, pages/index.js
=> splash뷰(index.js) 만들기

components/Buttons.js, components/Layouts.js, pages/guide.js, pages/index.js, pages/receiver/detail.js, pages/receiver/main.js, pages/sender/editor.js, pages/sender/editorBackground.js, pages/sender/editorFont.js, pages/sender/editorSticker.js, pages/sender/main.js, pages/sender/share.js, pages/sender/splash.js
Layouts 라는 컴포넌트로 감싸면 되게끔 만들었습니다.
=> 기본 레이아웃 잡기

pages/index.js
=> fix index.js

pages/sender/[main].js, pages/sender/share/[main].js
=> fix bug #26

pages/receiver/detail.js, styles/styles.scss
=> Fix #30 issue

components/Buttons.js, pages/_app.js, pages/sender/editor/[main].js
=> 기본 설정 수정 && 에디터 페이지 생성

package.json, pages/sender/editor.js, yarn.lock
=> add create png file feature

package.json, pages/sender/editor.js, yarn.lock
=> remove component-export

package.json, pages/sender/editor.js, yarn.lock
add modal feature in editor.js
=> add modal feature in editor.js

components/Cards.js, components/Header.js, components/Layouts.js, pages/receiver/detail.js, pages/receiver/main.js, pages/sender/main.js
=> [#38] 준비자 페이지 메인 화면 구현

components/ColorModal.js
* 뒤로가기 아이콘 색상 변경 필요
- 현재 검정색 -> 흰색 변경해야 함
#close #51
=> 에디터 배경색상 설정 모달 구성

components/FontModal.js, pages/celebrate.js, pages/create.js, pages/sender/editor.js, pages/sender/main.js
modify index.js page view && text->content
=> modify index.js page view && text->content

components/FontModal.js
=> [#57] 에디터 Font 모달 UI #1

pages/sender/editor.js, pages/sender/main.js, services/rollingService.js
=> connect with server

components/ColorModal.js, pages/create.js, pages/index.js, pages/sender/editor.js, pages/sender/main.js, services/rollingService.js
=> add get content&&author

components/Cards.js
=> connect data with Cards

services/rollingService.js
change baseURL to https://api.rollingpaper.site
=> change baseURL to https://api.rollingpaper.site

components/Cards.js, components/DeleteModal.js
=> add deleteModal feature

pages/sender/share.js
=> add share btn

components/Layouts.js, pages/receiver/main.js, pages/sender/main.js
fix body backgroundColor of main.js
=> fix body backgroundColor of main.js

components/Cards.js, pages/receiver/detail.js, pages/sender/editor.js
=> feat: Card 글자수 넘칠 때 깨지는 이슈 수정

components/Cards.js, components/Modal.js, pages/sender/main.js
feat: Modal component 리팩토링 및 deletePost 기능 추가  (#62)
=> feat: Modal component 리팩토링 및 deletePost 기능 추가  (#62)

components/Cards.js, pages/sender/main.js
=> feat: 실시간 posts 삭제 상황 반영

components/Cards.js, pages/index.js, pages/receiver/splash.js, pages/sender/detail.js
=> feat:modify editor

components/FontModal.js, pages/sender/editor.js
=> 에디터 높이 해상도 동적 대응

components/ColorModal.js, pages/sender/editor.js, pages/sender/main.js, pages/test.js
사진 배경에 띄우는 기능만 붙였습니다. 아직 서버랑 통신은 못합니다.
=> 사진 배경에 띄우기 (#96)

pages/sender/editor.js, pages/test.js, services/rollingService.js
feat: add post/get with server (#96)
=> feat: add post/get with server (#96)

components/StickerList.js, pages/_app.js, pages/sender/main.js
=> enhancement: 스티커 기능 변경사항 수정

pages/index.js, pages/receiver/detail.js, pages/receiver/splash.js, pages/sender/detail.js, pages/sender/share.js
fix: detail.js photo & add gif files(#96)
=> fix: detail.js photo & add gif files(#96)
